---
platform: linux
inputs:
- name: git-repo
outputs:
- name: distribution-repository
caches:
- path: maven
- path: gradle
- path: embedmongo
params:
- GRADLE_ENTERPRISE_URL: https://ge.spring.io
- CI: true
run:
  path: bash
  args:
    - -ec
    - |
      source /docker-lib.sh
      start_docker
      ${PWD}/git-repo/ci/scripts/build-project.sh

